### ISSUE TITLE
Improving the /houses endpoints

### ISSUE THREAD

**Issue by mathiasbynens** [TibiaData/tibiadata-api-go#198]
Currently, the only way to get a list of all houses and guildhalls in the game is to query

```
https://api.tibiadata.com/v3/houses/Antica/Venore
```

…replacing `Venore` with every city that has buildings for rent.

It would be lovely if either

```
https://api.tibiadata.com/v3/houses/Antica
```

…would give the complete list of buildings across all cities.

Alternatively (and I suspect you’ll prefer this option), it would be great if there was an API endpoint that returned all the cities with buildings, as listed in the Towns column on this page: https://www.tibia.com/community/?subtopic=houses

Currently, this list is:

```
Ab'Dendriel
Ankrahmun
Carlin
Darashia
Edron
Farmine
Gray Beach
Issavi
Kazordoon
Liberty Bay
Moonfall
Port Hope
Rathleton
Silvertides
Svargrond
Thais
Venore
Yalahar
```

…but any update can potentially change it.

**Comment by mathiasbynens** [comment]
Another minor thing I noticed is that `id`s are currently numbers, but they should be strings.

**Comment by tobiasehlert** [comment]
Hi @mathiasbynens,

Good idea, but I don't want to do too many upstream requests if the enduser only is looking for a few things. This would basically generate 18 upstream requests if someone only wants to look for one town and no more and the parsing time increases as well including that hosting tibiadata container as a non-fansite will make this request useless (due to ratelimiting). Sooo therefore I've not planned to introduce it at the moment :)

We do have some static information located in our [TibiaData/tibiadata-api-assets](https://github.com/TibiaData/tibiadata-api-assets) repository and you can get the latest data.json on `https://assets.tibiadata.com/data.json`.
There is inside the data one that is called `towns`, which is the exact list you mention above. Also under houses, you can find a list of the available houses including ID, town, world and so on.

Kind regards,
Tobias

**Comment by mathiasbynens** [comment]
I'd much rather rely on your `data.json` endpoint and its `towns` instead of hardcoding my own list. Thanks for the pointer!

**Comment by tobiasehlert** [comment]
Awesome, then I'll set the issue to closed. Get back here if there is some more question :)

**Comment by mathiasbynens** [comment]
Sounds good. Thanks again.

I just wanted to make sure this comment wasn't overlooked:

> Another minor thing I noticed is that `id`s are currently numbers, but they should [arguably] be strings.

**Comment by tobiasehlert** [comment]
@mathiasbynens yes, the houseid is supposed to be an integer in our API. tibia.com doesn't care as long as the value is passed in the request from tibiadata to them as a value, so since it's only numbers I think thats the most appropriate type :)

**Comment by mathiasbynens** [comment]
Alright. Fingers crossed CipSoft never introduces an ID larger than `Number.MAX_SAFE_INTEGER`, then :P Cfr. https://developer.twitter.com/en/docs/twitter-ids

Thanks for always responding so quickly! I really enjoy using the TibiaData API.
